<% from "tests.inc.yml" import build, calc_cache_key, restore_cache, setup_terraform -%>

<% macro setup_aws_creds() -%>
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
<%- endmacro -%>

<% macro setup_gcp_creds() -%>
    - name: Configure GCP Credentials
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
<%- endmacro -%>

name: Tests on Managed PostgreSQL

on:
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - cloud-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    <%- call build() -%>
    - name: Compute cache keys
      run: |
        << calc_cache_key()|indent >>
    <%- endcall %>


  setup-aws-aurora:
    runs-on: ubuntu-latest
    outputs:
      pghost: ${{ steps.pghost.outputs.stdout }}
    defaults:
      run:
        working-directory: .github/aws-aurora
    steps:
      << setup_terraform()|indent(2) >>

      << setup_aws_creds()|indent(2) >>

      - name: Setup AWS RDS Aurora
        env:
          TF_VAR_sg_id: ${{ secrets.AWS_SECURITY_GROUP }}
          TF_VAR_password: ${{ secrets.AWS_RDS_PASSWORD }}
          TF_VAR_vpc_id: ${{ secrets.AWS_VPC_ID }}
        run: |
          terraform apply -auto-approve

      - name: Store Terraform state
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: aws-aurora-tfstate
          path: .github/aws-aurora/terraform.tfstate
          retention-days: 1

      - name: Get RDS Aurora host
        id: pghost
        run: |
          terraform output -raw rds_cluster_endpoint

  test-aws-aurora:
    runs-on: ubuntu-latest
    needs: [setup-aws-aurora, build]
    steps:
    <<- restore_cache() >>

    # Run the test

    - name: Test
      env:
        EDGEDB_TEST_BACKEND_DSN: postgres://edbtest:${{ secrets.AWS_RDS_PASSWORD }}@${{ needs.setup-aws-aurora.outputs.pghost }}/postgres
      run: |
        edb server --bootstrap-only --backend-dsn=$EDGEDB_TEST_BACKEND_DSN --testmode
        edb test -j1 -v --backend-dsn=$EDGEDB_TEST_BACKEND_DSN

  teardown-aws-aurora:
    runs-on: ubuntu-latest
    needs: test-aws-aurora
    if: ${{ always() }}
    defaults:
      run:
        working-directory: .github/aws-aurora
    steps:
      << setup_terraform()|indent(2) >>

      << setup_aws_creds()|indent(2) >>

      - name: Restore Terraform state
        uses: actions/download-artifact@v2
        with:
          name: aws-aurora-tfstate
          path: .github/aws-aurora

      - name: Destroy AWS RDS Aurora
        run: terraform destroy -auto-approve
        env:
          TF_VAR_sg_id: ${{ secrets.AWS_SECURITY_GROUP }}
          TF_VAR_password: ${{ secrets.AWS_RDS_PASSWORD }}
          TF_VAR_vpc_id: ${{ secrets.AWS_VPC_ID }}

      - name: Overwrite Terraform state
        uses: actions/upload-artifact@v2
        with:
          name: aws-aurora-tfstate
          path: .github/aws-aurora/terraform.tfstate
          retention-days: 1
